routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group.
|
*/

Route::get('/', function () {
    return view('home');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['admin'])->group(function () {
	Route::resource('users', 'UsersController');
    Route::get('roles/{id}/users', function () {
        return redirect('/users');
    });
    
    //Route::get('tafels/refresh', 'TafelsController@something');
    Route::get('resetid/{table_id}', 'TafelsController@reset');
    Route::resource('tables', 'TafelsController', ['only' => [
        'create', 'store', 'edit', 'update', 'destroy'
    ]]);
    Route::get('tafels/refresh', 'TafelsController@refresh_tafels')->name('tafels.refresh');

    Route::get('roles', 'TafelsController@make_roles')->name('roles'); // TODO remove on production
});

Route::middleware(['auth'])->group(function () {
    Route::get('dashboard', 'HomeController@dashboard')->name('dashboard');
    Route::resource('tables', 'TafelsController', ['except' => [
        'create', 'store', 'edit', 'update', 'destroy'
    ]]);
    Route::get('records/{table_name}/create', 'RecordsController@create')->name('records.create');
    Route::post('records/{table_name}', 'RecordsController@store')->name('records.store');
	Route::get('records/{table_name}/{id}', 'RecordsController@show')->name('records.show');
	Route::get('records/{table_name}/{id}/edit', 'RecordsController@edit')->name('records.edit');
	Route::post('records/{table_name}/{id}', 'RecordsController@update')->name('records.update');
});

resources/views/dashboard.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    <div class="col-md-3">
                        <ul class="left-nav">
                            @foreach ($tables as $tafel)
                                <li><a href="{{ url('/tables/'.$tafel->id) }}"> {{ $tafel->table_name }}</a></li>
                            @endforeach
                        </ul>
                    </div>
                    <div class="col-md-9">
                        <table class="table table-bordered">
                          <thead>
                            <tr>
                              <th>Table Name</th>
                              <th>Description</th>
                              <th>Number of Records</th>
                            </tr>
                          </thead>
                          <tbody>
                                @foreach ($tables as $tafel)
                                    <tr>
                                      <th scope="row"><a href="{{ url('/tables/'.$tafel->id) }}"> {{ $tafel->table_name }}</a></th>
                                      <td>
                                        @if( $tafel->description )
                                        <b>Description:</b>&nbsp;{{ $tafel->description }}<br>
                                        @endif
                                        <b>Columns:</b><br>
                                        @foreach ($tafel->columns as $column)
                                            {{ $column }},&nbsp;
                                        @endforeach
                                      </td>
                                      <td>{{ $tafel->size }}</td>
                                    </tr>
                                @endforeach

                          </tbody>
                        </table>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/error.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Laravel</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Raleway:100,600" rel="stylesheet" type="text/css">

        <!-- Styles -->
        <style>
            html, body {
                background-color: #fff;
                color: #636b6f;
                font-family: 'Raleway', sans-serif;
                font-weight: 100;
                height: 100vh;
                margin: 0;
            }

            .full-height {
                height: 100vh;
            }

            .flex-center {
                align-items: center;
                display: flex;
                justify-content: center;
            }

            .position-ref {
                position: relative;
            }

            .top-right {
                position: absolute;
                right: 10px;
                top: 18px;
            }

            .content {
                text-align: center;
            }

            .title {
                font-size: 84px;
            }

            .links > a {
                color: #636b6f;
                padding: 0 25px;
                font-size: 12px;
                font-weight: 600;
                letter-spacing: .1rem;
                text-decoration: none;
                text-transform: uppercase;
            }

            .m-b-md {
                margin-bottom: 30px;
            }
        </style>
    </head>
    <body>
        <div class="flex-center position-ref full-height">
            @if (Route::has('login'))
                <div class="top-right links">
                    @if (Auth::check())
                        <a href="{{ url('/home') }}">Home</a>
                    @else
                        <a href="{{ url('/login') }}">Login</a>
                        <a href="{{ url('/register') }}">Register</a>
                    @endif
                </div>
            @endif

            <div class="content">
                <div class="title m-b-md">
                    Error!
                </div>

                <div class="links">
                    You don't seem to have the right to access that resource
                </div>
            </div>
        </div>
    </body>
</html>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    @if (Auth::user())
                        You are logged in!
                    @else
                        You must login
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/record-create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Create new record in the <strong><em>{{ $table_name }}</em></strong> table</div>

                <div class="panel-body">
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <p>- {{ $error }}</p>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    {!! Form::open(array('url' => route('records.store', [$table_name]))) !!}
                        <table class="table table-bordered table-striped">
                            <thead>
                                <th>Column</th>
                                <th>Value</th>
                            </thead>
                                @foreach ($fields as $column => $value)
                                <tr>
                                    <td>{{ $column }}</td>
                                    <td>{!! $value['field'] !!}</td>
                                </tr>
                                @endforeach
                        </table>
                        {!! Form::submit('Save Record') !!}
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/record-edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Editing Record</div>

                <div class="panel-body">
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <p>- {{ $error }}</p>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    {!! Form::open(array('url' => route('records.update', [$table_name, $record->id]))) !!}
                        <table class="table table-bordered table-striped">
                            <thead>
                                <th>Column</th>
                                <th>Value</th>
                            </thead>
                                @foreach ($fields as $column => $value)
                                <tr>
                                    <td>{{ $column }}</td>
                                    <td>{!! $value['field'] !!}</td>
                                </tr>
                                @endforeach
                        </table>
                        {!! Form::submit('Save Record') !!}
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/record-show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">Showing record <strong>{{ $record->id }}</strong> on the <strong><em>{{ $table_name }}</em></strong> table</div>

                <div class="panel-body">
                    <table class="table table-bordered table-striped">
                        <thead>
                            <th>Column</th>
                            <th>Value</th>
                        </thead>
                        @foreach ($record as $column => $value)
                        <tr>
                            <td>{{ $column }}</td>
                            <td>{{ $value }}</td>
                        </tr>
                        @endforeach
                    </table>
                    @if(Uza::owns($table_name, $record))
                        <a class="btn btn-info" href="{{ route('records.edit', [$table_name, $record->id]) }}">Edit This Record</a>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/table-edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading"><h2>Editing table <b><em>{{ $table->table_name }}</em></b></h2></div>

                <div class="panel-body">
                    {{ Form::open([ 'method' => 'PATCH', 'route' => ['tables.update', $table->id] ]) }}
                        <table class="table table-bordered table-striped">
                                <tr>
                                    <td>Viewable By</td>
                                    <td>
                                        @foreach($roles as $role)
                                            {{ str_plural($role->display_name) }}&nbsp;&nbsp;{{ Form::checkbox('viewable_by[]', $role->name, in_array($role->name, explode(',', $table->viewable_by))) }}<br>
                                        @endforeach
                                    </td>
                                </tr>
                                <tr>
                                    <td>Editable By</td>
                                    <td>
                                        @foreach($roles as $role)
                                            {{ str_plural($role->display_name) }}&nbsp;&nbsp;{{ Form::checkbox('editable_by[]', $role->name,  in_array($role->name, explode(',', $table->editable_by))) }}<br>
                                        @endforeach
                                    </td>
                                </tr>
                                <tr>
                                    <td>Table Description</td>
                                    <td>{{ Form::textarea('description', $table->description, ['class' => 'form-control', 'rows'=>3]) }}</td>
                                </tr>
                        </table>
                        <h2>Columns</h2>
                        <table class="table table-bordered table-striped">
                            <tr>
                                <th>Column Name</th>
                                <th>Type</th>
                                <th>Validation Rules</th>
                                <th>Acceptable Values</th>
                            </tr>
                            @foreach($table->columns as $col)
                                <tr>
                                    <td>{{ $col->column_name }}</td>
                                    <td>
                                        {{ Form::select($col->id.'__field_type', ['text'=>'Text', 'date'=>'Date', 'checkbox'=>'Check Boxes', 'radio'=>'Radio Buttons', 'select'=>'Drop Down'], $col->field_type, ['class'=>'form-control']) }}
                                    </td>
                                    <td>{{ Form::text($col->id.'__validation_rules', $col->validation_rules, ['class' => 'form-control']) }}</td>
                                    <td>{{ Form::text($col->id.'__acceptable_values', $col->acceptable_values, ['class' => 'form-control']) }}</td>
                                </tr>
                            @endforeach
                        </table>
                        {{ Form::submit('Save', ['class'=>'btn btn-info']) }}
                        <a href="{{ url('resetid/'.$table->id ) }}" role="button" class="btn btn-danger">Reset IDs</a>
                    {{ Form::close() }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/table-show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">

        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading"><h2>{{ $table->table_name }}</h2></div>

                <div class="panel-body">
                    <div class="col-md-12">
                        Other Available Tables: <br>
                        <span class="">
                            @foreach ($tables as $tafel)
                                <a href="{{ url('/tables/'.$tafel->id) }}" class="btn btn-info" role="button"> {{ $tafel->table_name }}</a>
                            @endforeach  
                            <p>&nbsp;</p>
                            @if(\Auth::user()->hasRole('admin') && !in_array($tafel->table_name, config('constants.system_tables')))
                                <a href="{{ route('tables.edit', $table->id) }}" class="btn btn-danger" role="button">Edit This Table</a>
                            @endif  
                            @if(Uza::can('edit', $table->table_name))
                                <a href="{{ url('/records/'.$table->table_name.'/create') }}" class="btn btn-info" role="button"> New Record</a>
                            @endif                     
                        </span>
                    </div>
                    <div class="col-md-12">
                        {{ $records->links() }}  
                        <div class="table-responsive">
                            <table class="table table-bordered table-striped">
                              <thead>
                                <tr>
                                    @foreach ($tables[$table->table_name]->columns as $column_name)
                                        <th>{{ $column_name }}</th>
                                    @endforeach
                                </tr>
                              </thead>
                              <tbody>
                                    @foreach ($records as $row)
                                        <tr>
                                            @foreach ($row as $column)
                                                <td>{{ $column }}</td>
                                            @endforeach
                                          
                                            @if(isset($row->id))
                                                <td>
                                                    <a href="{{ url('records/'.$table->table_name, $row->id) }}">Details</a>
                                                </td>
                                            @endif
                                        </tr>
                                    @endforeach
                              </tbody>
                            </table>                            
                        </div>
                        {{ $records->links() }}                    
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/tables.blade.php
@extends('layouts.app')

@section('content')
<?php
  if(\Auth::user()->hasRole('admin')) // Check once to avoid running the method over and over in the loops
    $is_admin = true;
  else 
    $is_admin = false;
?>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    <div class="col-md-3">
                        <ul class="left-nav">
                            @foreach ($tables as $tafel)
                                <li><a href="{{ url('/tables/'.$tafel->id) }}"> {{ $tafel->table_name }}</a></li>
                            @endforeach
                            <br>
                            @if($is_admin)
                                <a href="{{ url('tafels/refresh') }}" class="btn btn-info" role="button">Refresh Tables</a>
                            @endif
                        </ul>
                    </div>
                    <div class="col-md-9">
                        <table class="table table-bordered">
                          <thead>
                            <tr>
                              <th>Table Name</th>
                              <th>Columns</th>
                              <th>Number of Records</th>
                              @if($is_admin)
                              <th>Actions</th>
                              @endif
                            </tr>
                          </thead>
                          <tbody>
                                @foreach ($tables as $tafel)
                                    <tr>
                                      <th scope="row"><a href="{{ url('/tables/'.$tafel->id) }}"> {{ $tafel->table_name }}</a></th>
                                      <td>
                                        @foreach ($tafel->columns as $column)
                                            {{ $column }},&nbsp;
                                        @endforeach
                                      </td>
                                      <td>{{ $tafel->size }}</td>
                                      @if($is_admin)
                                      <td>
                                          <a href="{{ url('/tables/'.$tafel->id.'/edit') }}"> Edit</a>
                                      </td>
                                      @endif
                                    </tr>
                                @endforeach

                          </tbody>
                        </table>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/user-edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">{{ $user->fname }} {{ $user->lname }}</div>

                <div class="panel-body">
                    {{ Form::open([ 'method' => 'PATCH', 'route' => ['users.update', $user->id] ]) }}
                        <table class="table table-bordered table-striped">
                                <tr>
                                    <td>First Name</td>
                                    <td>{{ Form::text('fname', $user->fname, ['class' => 'form-control']) }}</td>
                                </tr>
                                <tr>
                                    <td>Last Name</td>
                                    <td>{{ Form::text('lname', $user->lname, ['class' => 'form-control']) }}</td>
                                </tr>
                                <tr>
                                    <td>Username</td>
                                    <td> {{ Form::text('username', $user->username, ['class' => 'form-control']) }} </td>
                                </tr>
                                <tr>
                                    <td>Email</td>
                                    <td> {{ Form::email('email', $user->email, ['class' => 'form-control']) }} </td>
                                </tr>
                                <tr>
                                    <td>Roles</td>
                                    <td>
                                        @foreach($roles as $role)
                                            {{ $role->display_name }}&nbsp;{{ Form::checkbox('roles[]', $role->id, $user->hasRole($role->name)) }}<br>
                                        @endforeach
                                    </td>
                                </tr>
                                <tr>
                                    <td>Set Password</td>
                                    <td> {{ Form::password('password', $value = null, $attributes = ['class' => 'form-control']) }} </td>
                                </tr>
                                <tr>
                                    <td>State</td>
                                    <td>{{ $user->state }}</td>
                                </tr>
                        </table>
                        {{ Form::submit('Save', ['class'=>'btn btn-info']) }}
                    {{ Form::close() }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/user-profile.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">{{ $user->fname }} {{ $user->lname }}</div>

                <div class="panel-body">
                    <table class="table table-bordered table-striped">
                        <tr>
                            <td>Name</td>
                            <td>{{ $user->fname }} {{ $user->lname }}</td>
                        </tr>
                        <tr>
                            <td>Username</td>
                            <td> {{ $user->username }} </td>
                        </tr>
                        <tr>
                            <td>Roles</td>
                            <td>
                                @foreach ($user->roles as $role)
                                    {{ $role->name }}&nbsp;
                                @endforeach
                            </td>
                        </tr>
                        <tr>
                            <td>Registered On</td>
                            <td> {{ $user->created_at }} </td>
                        </tr>
                        <tr>
                            <td>Active</td>
                            <td>{{ $user->state }}</td>
                        </tr>
                    </table>
                    @if( \Auth::user()->hasRole('admin') || \Auth::user()->id == $user->id )
                        <a class="btn btn-info" href="{{ route('users.edit', [$user->id]) }}">Edit Profile</a>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/users.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    <div class="col-md-3">
                        <ul class="left-nav">
                            @foreach ($roles as $role)
                                <li><a href="{{ url('/roles/'.$role['id'].'/users') }}"> {{ str_plural($role['display_name']) }}</a></li>
                            @endforeach
                        </ul>
                    </div>
                    <div class="col-md-9">
                        <table class="table table-bordered">
                          <thead>
                            <tr>
                              <th>Name</th>
                              <th>Roles</th>
                              <th>Email</th>
                            </tr>
                          </thead>
                          <tbody>                                
                                @foreach ($users as $user)
                                    <tr>
                                      <th scope="row"><a href="{{ url('/users/'.$user['id']) }}"> {{ $user['fname'] }} {{ $user['lname'] }}</a></th>
                                      <td>
                                        @foreach ($user->roles as $role)
                                            {{ $role->name }},&nbsp;
                                        @endforeach
                                      </td>
                                      <td>{{ $user['email'] }}</td>
                                    </tr>                                    
                                @endforeach

                          </tbody>
                        </table>                       
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection